#variable
vpc_cidr_block1 = "10.0.0.0/16"
sub_cidr_block1 = "10.0.1.0/24"
env_prefix = "dev"
az = "us-west-2a"
myip = "0.0.0.0/0"
server-key = "org-key"
instance_type = "t2.micro"
public_key_location = "/home/shubham/.ssh/id_rsa.pub"
private_key_location = "/home/shubham/.ssh/id_rsa"